# Serverless Framework
# REQUIRE MANUAL CONFIG FOR LAMBDA@EDGE

service: gttlalog

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  environment:
    GTT_PASSWORD: ${env:GTT_PASSWORD}

# stage and region
stage: dev
region: us-east-1

functions:
  log:
    handler: log.handler