# Serverless Framework

# Application Configuration
plugins:
   - serverless-plugin-cloudfront-lambda-edge

service: gttlalog

provider:
  name: aws
  runtime: nodejs6.10

# stage and region
stage: dev
region: us-east-1

functions:
  log:
    handler: log.handler