# Serverless Framework

# Application Configuration
config:
  bucket: &bucket "arn:aws:s3:::BUCKET_NAME"

service: gttla

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "s3:ListBucket"
           - "s3:ListObjects"
           - "s3:PutObject"
           - "s3:PutObjectAcl"
         Resource:
          Fn::Join:
            - ""
            - - *bucket
              - "/*"

# stage and region
stage: dev
region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
